# Generated by Django 5.2.7 on 2025-10-22 02:41

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='tempUser', max_length=200, unique=True)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
                ('isVendor', models.CharField(blank=True, max_length=200, null=True)),
                ('shiftIn', models.CharField(blank=True, max_length=200, null=True)),
                ('shiftOut', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=attendance.models.user_directory_path)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
                ('isRegularOrNormal', models.CharField(blank=True, max_length=200, null=True)),
                ('approvedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=400, null=True)),
                ('isCheckin', models.CharField(blank=True, max_length=400, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.user_detail')),
            ],
        ),
    ]
