# Generated by Django 5.2.7 on 2025-10-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='shiftIn',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='shiftOut',
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='phone',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
