# Generated by Django 5.2.7 on 2025-10-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_user_detail_shiftin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
    ]
