# Generated by Django 5.2.7 on 2025-10-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='approvedBy',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='isRegularOrNormal',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.user_detail'),
        ),
    ]
