# Generated by Django 5.2.7 on 2025-10-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_attendance_approvedby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='isCheckin',
        ),
    ]
