# Generated by Django 5.2.7 on 2025-10-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_attendance_ischeckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='isCheckin',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
