# Generated by Django 5.2.7 on 2025-10-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_ischeckin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='isCheckin',
            field=models.BooleanField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='isVendor',
            field=models.BooleanField(blank=True, max_length=200, null=True),
        ),
    ]
